### ISSUE TITLE
Locations with timeline is really slow

### ISSUE THREAD

**Issue by adiglase** [ExpDev07/coronavirus-tracker-api#104]
Can we searching for timeline just for a country? So, timelines with country code

**Comment by ExpDev07** [comment]
Not sure what you mean, are you talking about /v2/locations?country_code=US&timelines=1?

**Comment by adiglase** [comment]
Ohh.. I didnt know its exist. But still really slow

**Comment by ExpDev07** [comment]
Well, yes, it's slow because of the large amount of data you get when retrieving with timelines. 

When I'm hitting the endpoints right now:
``https://coronavirus-tracker-api.herokuapp.com/v2/locations?country_code=US`` (200ms)
``https://coronavirus-tracker-api.herokuapp.com/v2/locations?country_code=US&timelines=1`` (1200ms)

Ideally you shouldn't be grabbing all timelines at the same time, but rather pick a specific country and load its timelines through ``https://coronavirus-tracker-api.herokuapp.com/v2/locations/:id`` (60ms) when needed.
