### ISSUE TITLE
US Locations Missing

### ISSUE THREAD

**Issue by uponatime2019** [ExpDev07/coronavirus-tracker-api#157]
https://coronavirus-tracker-api.herokuapp.com/v2/locations?country_code=US

I just check above API, last night all fine, it show latest and latest by locations. But now just have a location, no addional data.

`{"latest":{"confirmed":43847,"deaths":557,"recovered":0},"locations":[{"coordinates":{"latitude":"37.0902","longitude":"-95.7129"},"country":"US","country_code":"US","id":225,"last_updated":"2020-03-24T05:07:57.655924Z","latest":{"confirmed":43847,"deaths":557,"recovered":0},"province":""}]}`

**Comment by ExpDev07** [comment]
Unfortunately, our main data provider, JHU, has decided to track U.S.A. on country-level, as well as with many other nations as well. This is probably due to overwhelming work of keeping up with every state/province as well. 

We provide an additional data-source if you're looking for U.S. specific locations. The data is provided by CSBS (https://www.csbs.org/information-covid-19-coronavirus). For example:

* View locations in california: https://coronavirus-tracker-api.herokuapp.com/v2/locations?source=csbs&state=California.
* View county of San Mateo (has an ID of 105): https://coronavirus-tracker-api.herokuapp.com/v2/locations/105?source=csbs.
