### ISSUE TITLE
Move v1 to FastAPI

### ISSUE THREAD

**Issue by Kilo59** [ExpDev07/coronavirus-tracker-api#206]
Version 1 of the API is still using Flask mounted as a wsgi application.
https://fastapi.tiangolo.com/advanced/wsgi/

https://github.com/ExpDev07/coronavirus-tracker-api/tree/master/app/routes/v1

We can remove the Flask dependency and move everything to the `ASGI` based FastAPI which should increase the total throughput of the API.
https://www.encode.io/articles/hello-asgi

**Comment by ibhuiyan17** [comment]
Can I take a shot at this?

**Comment by ExpDev07** [comment]
@ibhuiyan17 Sure, if you wish!

**Comment by ibhuiyan17** [comment]
@ExpDev07  @Kilo59 
Hey guys, just checking in. 

So I believe I have v1 "working" with FastAPI but it's not passing the tests because it currently returns a dictionary which may have non-deterministic ordering. My guess is adding models for the v1 endpoints (like the ones that exist for v2) might fix this if the schema matches the order in the json file that it's being tested against.

Let me know if this sounds like a reasonable solution. Another alternative I can think of is passing the outputs through a sort function before checking if they're equal, but that might be a bit tedious and counter intuitive if you guys want v1 to work similarly to v2 anyways.

**Comment by ExpDev07** [comment]
@ibhuiyan17 that shouldn't really be the issue. Open a PR ?

**Comment by Kilo59** [comment]
My guess is you are using the flask testing client instead of the FastAPI testing client. Dictionaries haven ordered since 3.6
But it'll be much easier to debug once you open a PR.

**Comment by ibhuiyan17** [comment]
I switched it over to the FastAPI testing client but still getting the issue. I'll open a PR

**Comment by ibhuiyan17** [comment]
I see now, I was thinking about it backwards. It passed the tests when I did json.loads(expected). I'll open a PR after cleaning up my changes a bit. Thanks!
