### ISSUE TITLE
Last 24 hours?

### ISSUE THREAD

**Issue by saifalfalah** [ExpDev07/coronavirus-tracker-api#30]
Is it possible to get just the new confirmed cases in the last 24 hours?

**Comment by ExpDev07** [comment]
At the moment no, you can, however, get the confirmed cases the last 24 hours by taking the most recent date in the history and subtracting it with the the day before.

**Comment by saifalfalah** [comment]
That's what I was thinking. Does the number of cases have an impact on how many people have been cured? What I mean is, let's say if there are 100 people infected today, and 10 get cured and 20 more get infected, will the new number tomorrow be 120 or 110?

**Comment by ExpDev07** [comment]
Yes, it does. The latest history can show lower numbers than before if recoveries occur more quickly than confirms.

**Comment by saifalfalah** [comment]
So that means that (PrevDay - Today) will not give the correct number of new cases in the last 24 hours, right?

**Comment by ExpDev07** [comment]
@saifalfalah Yes, you are correct :/. Doesn't look like Johns Hopkins CSSE provides the amount of new confirmed cases....

**Comment by pizzavore** [comment]
Hmmm... That's not how I understand the data.  I don't think the number of confirmed cases can ever decrease. I believe all the data metrics can only increase.  I believe the answer to saifalfalah's question is: the number of confirmed cases will be 120, and the recovered cases will increase by 10.

**Comment by ExpDev07** [comment]
@pizzavore is probably right. I have seen it decrease before, but the explanation could be that the initial amount was wrong and it was lowered to be corrected. I understood it as currently infected, but when you think about it doesn’t make any sense why’d they call it confirmed then.

**Comment by pizzavore** [comment]
Good point, I agree they could decrease due to a correction.  

Currently "active" cases  =  confirmed - (deaths + recovered)   

But I suspect many of the confirmed cases will never be reported as "recovered" if people are recovering in their homes.

**Comment by sallu-tech** [comment]
Hi
I am building a website in bootstrap and core php. So I wanted to ask can I use this api in php?

**Comment by ExpDev07** [comment]
@sallu-tech 

> I am building a website in bootstrap and core php. So I wanted to ask can I use this api in php?

Yes, you certainly can. You have the option of just retrieving the data client-side in JavaScript, or on the server with PHP. I would suggest using PHP if you're planning on doing some extensive calculations with the data. Look up how to make a GET request to an URL and parse the json in your desired language, because that's how you get the data.

> And also tell me when does this api gets updated to get the updated number of cases?

The data comes from the [2019 Novel Coronavirus (nCoV) Data Repository](https://github.com/CSSEGISandData/2019-nCoV), provided by JHU CCSE. It is programmatically retrieved, re-formatted and stored in the cache for one hour. 

So to answer your question, it updates whenever JHU CCSE updates it, with the delay of maximum an hour.
